#!/bin/sh

port=44444
jruby=/home/nao/sandbox/mirah/workarea/jruby/bin/jruby

lsof -i:$port | grep java 2>&1 1>/dev/null
if [ $? -ne 0 ]; then
    echo "booting qmirahc server..."
    $jruby mirah_server.rb &
    lsof -i:$port | grep java 2>&1 1>/dev/null
    while [ $? -ne 0 ]; do
        sleep 1
        lsof -i:$port | grep java
    done
fi

nc localhost $port <<EOF
run -d `pwd` $@
EOF
